//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceExamen
{
    using System;
    using System.Data.SqlClient;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="App", Namespace="http://schemas.datacontract.org/2004/07/WsApiexamen")]
    public partial class App : object
    {
        
        private string DescripcionField;
        
        private string NombreField;
        
        private int idExamenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idExamen
        {
            get
            {
                return this.idExamenField;
            }
            set
            {
                this.idExamenField = value;
            }
        }

        public static implicit operator int(App v)
        {
            throw new NotImplementedException();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceExamen.AppService")]
    public interface AppService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppService/AgregarExamen", ReplyAction="http://tempuri.org/AppService/AgregarExamenResponse")]
        System.Threading.Tasks.Task<int> AgregarExamenAsync(ServiceExamen.App app);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppService/ActualizarExamen", ReplyAction="http://tempuri.org/AppService/ActualizarExamenResponse")]
        System.Threading.Tasks.Task<int> ActualizarExamenAsync(ServiceExamen.App app);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppService/EliminarExamen", ReplyAction="http://tempuri.org/AppService/EliminarExamenResponse")]
        System.Threading.Tasks.Task<int> EliminarExamenAsync(ServiceExamen.App app);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppService/ConsultarExamen", ReplyAction="http://tempuri.org/AppService/ConsultarExamenResponse")]
        System.Threading.Tasks.Task<ServiceExamen.App> ConsultarExamenAsync(int idcontacto, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppService/mostrarExamenes", ReplyAction="http://tempuri.org/AppService/mostrarExamenesResponse")]
        System.Threading.Tasks.Task<ServiceExamen.App[]> mostrarExamenesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface AppServiceChannel : ServiceExamen.AppService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class AppServiceClient : System.ServiceModel.ClientBase<ServiceExamen.AppService>, ServiceExamen.AppService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AppServiceClient() : 
                base(AppServiceClient.GetDefaultBinding(), AppServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_AppService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AppServiceClient.GetBindingForEndpoint(endpointConfiguration), AppServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AppServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AppServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }


        
        public System.Threading.Tasks.Task<int> AgregarExamenAsync(ServiceExamen.App app)
        {
            return base.Channel.AgregarExamenAsync(app);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarExamenAsync(ServiceExamen.App app)
        {
            return base.Channel.ActualizarExamenAsync(app);
        }
        
        public System.Threading.Tasks.Task<int> EliminarExamenAsync(ServiceExamen.App app)
        {
            return base.Channel.EliminarExamenAsync(app);
        }
        
        public System.Threading.Tasks.Task<ServiceExamen.App> ConsultarExamenAsync(int idcontacto, string Nombre, string Descripcion)
        {
            return base.Channel.ConsultarExamenAsync(idcontacto, Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task<ServiceExamen.App[]> mostrarExamenesAsync()
        {
            return base.Channel.mostrarExamenesAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_AppService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_AppService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:49579/AppService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AppServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_AppService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AppServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_AppService);
        }

        internal SqlDataReader EliminarExamenAsync(int id)
        {
            throw new NotImplementedException();
        }

        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_AppService,
        }
    }
}
